repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.5
    hooks:
    -   id: ruff
        args: [--fix]
    -   id: ruff-format

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
    -   id: pyupgrade
        args: [--py38-plus, --py39-plus, --py310-plus, --py311-plus]
        